FOLDER_TST: /home/armine/tst
FOLDER_OUT: /home/armine/out
FOLDER_1: /home/armine/folder1
FOLDER_2: /home/armine/folder2
count: 3
ip: 0.0.0.0
user: armine
passwd: "1818"
pkgname: p7zip-full
type: 7z